### ISSUE TITLE
Unable to run it

### ISSUE THREAD

**Issue by musictopia2** [StickMick/BYOC#5]
When I tried the last version, I get an error saying refusing to connect.  It means that whatever changes i would make, i have no way currently to test to see if i get the same results to make sure nothing is broken.

**Comment by StickMick** [comment]
Sorry, I should add a getting started to the readme.

I've swapped the structure around a bit, the game is now on the blazor server and the commandline is just connecting to a test hub on the server.

You'll need to start the server, then run the commandline and it'll connect to the hub and shutdown.
